version: "3.8"
services:
  shell:
    build: ./shell
    ports:
      - "3000:80"
    depends_on:
      - auth-mfe
      - user-mfe
      - product-mfe
      - order-mfe

  auth-mfe:
    build: ./microfrontends/auth-mfe
    ports:
      - "3001:80"

  user-mfe:
    build: ./microfrontends/user-mfe
    ports:
      - "3002:80"

  product-mfe:
    build: ./microfrontends/product-mfe
    ports:
      - "3003:80"

  order-mfe:
    build: ./microfrontends/order-mfe
    ports:
      - "3004:80"
