version: '3.8'

services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - database

  frontend:
    build:
      context: ./FE_React
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrongPassword!"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
