name: Backend CI/CD
uses: actions/upload-artifact@v3
  with:
    name: backend-artifact
    path: publish/
on:
  push:
    branches:
      - develop-main
  pull_request:
    branches:
      - develop-main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.1.x' # Nếu dùng .NET 8, đổi thành '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/clean-architecture-template.sln

      - name: Build
        run: dotnet build src/clean-architecture-template.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test src/clean-architecture-template.sln --configuration Release --no-build --verbosity normal

      - name: Publish
        run: dotnet publish src/CleanArchitectureTemplate.API/CleanArchitectureTemplate.API.csproj -c Release -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-artifact
          path: publish/
