name: Frontend CI/CD
uses: actions/upload-artifact@v3
  with:
    name: frontend-artifact
    path: FE_React/dist
on:
  push:
    branches:
      - develop-main
  pull_request:
    branches:
      - develop-main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Nếu dùng Node 20, đổi thành '20'

      - name: Install dependencies
        run: |
          cd FE_React
          npm install

      - name: Build project
        run: |
          cd FE_React
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-artifact
          path: FE_React/dist
